### ISSUE TITLE
Are you agree PR with HTTPS Support ?

### ISSUE THREAD

**Issue by patsevanton** [one-mINd/harbor_ansible_role#11]
Hello! Thanks for role harbor.
Are you agree PR with HTTPS Support ?

**Comment by one-mINd** [comment]
Hello! Thanks for the issue 
Yes, we will agree PR after a little review

**Comment by patsevanton** [comment]
Sorry. Not now. Later.

**Comment by patsevanton** [comment]
I am sorry. May be not created PR
